### ISSUE TITLE
ImportError on arm64 (Mac OSX M1) with jq 1.5.0 and 1.6.0

### ISSUE THREAD

**Issue by agmond** [mwilliamson/jq.py#100]
## Environment
- **Platform**: arm64 (Mac OSX M1)
- **Python Version**: 3.8
- **jq.py Version**: Issue observed with 1.5.0 and 1.6.0, works fine with 1.4.1

## Description
Starting from version 1.5.0, importing the `jq` module results in an ImportError. This issue persists in version 1.6.0. However, version 1.4.1 does not exhibit this problem.

## Steps to Reproduce
1. Install jq.py 1.5.0 or 1.6.0 using `pip`.
2. Attempt to `import jq` in a Python 3.8 environment on an arm64 Mac (OSX M1).

## Expected Behavior
The module should import without any errors, as it does in version 1.4.1.

## Actual Behavior
An ImportError is thrown, indicating a missing symbol in the namespace:
```
>>> import jq
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/path/to/python3.8/site-packages/jq.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_jq_compile'
```

The wheel installed by pip is `jq-1.5.0-cp38-cp38-macosx_11_0_arm64.whl` (or `jq-1.6.0-cp38-cp38-macosx_11_0_arm64.whl`).

It would be greatly appreciated if this issue could be looked into, as it impacts usability on the mentioned platform and version. Thank you for your assistance and hard work on this project!

**Comment by mwilliamson** [comment]
Do you get the issue if you install 1.6.0 using the sdist instead of the wheel?

**Comment by agmond** [comment]
@mwilliamson 
No. When using sdist it works as expected.
The name of the wheel that was built during the installation is `jq-1.6.0-cp38-cp38-macosx_12_0_arm64.whl`.

**Comment by mwilliamson** [comment]
Unfortunately I don't have a MacOS machine to test with, so my ability to debug is limited.

Looking at the list of wheels, the file size of that wheel is suspiciously low. However, based purely on file size, it seems like it might only be that specific combination of Python, OS and architecture that's affected. If you install using a different version of Python, do you get the same issue?

**Comment by agmond** [comment]
When installing jq v1.6.0 on Python 3.11 (instead of 3.8) I don't get that error

**Comment by mwilliamson** [comment]
Ah, seems like a result of this issue with CPython 3.8 on MacOS arm64: https://cibuildwheel.readthedocs.io/en/stable/faq/#macos-building-cpython-38-wheels-on-arm64

I've deleted the wheels for 1.5.0 and 1.6.0. I'm not sure whether I'll try to produce wheels for CPython 3.8 on MacOS arm64 in the future: given you're the first person to report the issue (although not necessarily the first to have it), that might be a rare enough combination that being able to install from the sdist is good enough?

**Comment by agmond** [comment]
Thanks, I'm OK with this.
Please note that future versions of `jq.py` will still suffer from this issue when using CPython 3.8 on MacOS arm64, so wheels should not be built for this combination of CPython 3.8 & MacOS arm64.

**Comment by mwilliamson** [comment]
Closing since I think this is all sorted.
