### ISSUE TITLE
Specify jq command-line options

### ISSUE THREAD

**Issue by msbc42** [mwilliamson/jq.py#102]
Is it possible to specify command-line options for jq? In particular I want to call jq with '-cr'.

**Comment by mwilliamson** [comment]
Could you explain a little more about your use case and why the existing functionality isn't sufficient? For instance, if you want to get the JSON string that jq produces, you should be able to use `first()` or `all()`.

**Comment by mwilliamson** [comment]
Closing since I don't think there's anything to be done without more information.
