### ISSUE TITLE
Inconsistency with the native JQ library 

### ISSUE THREAD

**Issue by bivas6** [mwilliamson/jq.py#112]
There appears to be a discrepancy in behavior between the Python implementation of jq and the native jq library. Specifically, certain queries yield different results when executed in the Python version compared to the native implementation. This inconsistency can lead to unexpected outcomes and complicates the debugging process for users relying on the Python library to replicate the same functionality as the native jq library.

Steps to Reproduce:
	1.	Execute the following query using the native jq library: 
	`echo '{"list":[{"a":["*"],"b":["*"],"c":["*"]}, {}]}' | jq 'try .list[] | select(.a[] == "*" or .a[] == "") | select(.b[] == "*") | select(.c[] == "*") | if . then {"result": true, "match": ., "field_name": "Rules"} else {"result": false} end'`
	2.	Execute the same query using the Python implementation of jq:
```
import jq

jq.compile('try .list[] | select(.a[] == "*" or .a[] == "") | select(.b[] == "*") | select(.c[] == "*") | if . then {"result": true, "match": ., "field_name": "Rules"} else {"result": false} end').input_text('{"list":[{"a":["*"],"b":["*"],"c":["*"]}, {}]}')
```

Expected Result:
The results should be identical, reflecting the same output for both the native jq and its Python counterpart.

I tried with latest. version and with 1.6.0, and also using value_text, values etc.

**Comment by mwilliamson** [comment]
Could you post the output you're getting for each with a minimal example? It would also help if you could minimise the query, assuming there are smaller examples that reproduce the issue.

**Comment by bivas6** [comment]
OK, so much smaller example is:

`echo '{"list":[{"a":["*"]}, {}]}' | jq 'try .list[] | select(.a[] == "*")'`

and:
```
import jq

jq.compile('try .list[] | select(.a[] == "*")').input_text('{"list":[{"a":["*"]}, {}]}')
```
the key is the empty object in the second entry of the array. It can also be with entries that doesn't match the pattern, for example: `{"asd": []}`

**Comment by bivas6** [comment]
The result from jq is :
```{
  "a": [
    "*"
  ]
}```

from the python library is "ValueError"

**Comment by mwilliamson** [comment]
Could you post the full error you're seeing?

**Comment by bivas6** [comment]
`Cannot iterate over null (null)`

**Comment by bivas6** [comment]
Just noticed that if I removing the `try` statement from the beginning, native jq gives:
```
-> echo '{"list":[{"a":["*"]}, {}]}' | jq '.list[] | select(.a[] == "*")' 
{
  "a": [
    "*"
  ]
}
jq: error (at <stdin>:1): Cannot iterate over null (null) 
```

**Comment by mwilliamson** [comment]
When an error is encountered with a particular value, it looks like jq prints an error to stdin and continues processing the next value, whereas these bindings will throw an exception.

It looks like there's a difference between jq 1.6 and jq 1.7 in how `try` is parsed. In 1.7, you can get rid of the error by moving the `try` to the `select` instead i.e. `.list[] | try select(.a[] == "*")`.

**Comment by bivas6** [comment]
Question is why the result is different than the "native" jq? Is it processed in a different order? 
as a workaround your solution is good, but ultimately I would prefer to get the same results..

**Comment by mwilliamson** [comment]
I don't think it's down to processing order, but a choice in how errors are handled: jq continues (and prints the error to stdin), whereas these bindings throw an exception (and therefore no value is returned).

**Comment by bivas6** [comment]
I see, I think jq is working more "greedy" once it has some result it bring it back, while the python library trying to accumulate all the results and return it.
for example, changing the input to: 
`{"list":[{},{"a":["*"]}, {}]}`
will yield only an error: `jq: error (at <stdin>:1): Cannot iterate over null (null)`

**Comment by bivas6** [comment]
OK, I'll close this one
