### ISSUE TITLE
pre-commit hooks to sort json by jq

### ISSUE THREAD

**Issue by Freed-Wu** [mwilliamson/jq.py#115]
Can we have a pre-commit hook to sort json by jq like https://github.com/lambdalisue/vim-nerdfont/blob/master/.github/workflows/jq.yml ?

**Comment by mwilliamson** [comment]
Sorry, I'm not sure what you're requesting. Could you explain a little further?

**Comment by Freed-Wu** [comment]
1. jq.py has a CLI port: `python -m jq --help` to do something like jq
2. jq.py has a pre-commit hook to run `diff <(python -m jq -S XXX.jq) XXX.jq` to know if XXX.jq is sorted.
3. User can add the hook to their project. when they `git commit`, the hook will be executed to check the json be `git add`ed.

https://pre-commit.com/

**Comment by mwilliamson** [comment]
I think that's outside the scope of the project, I'm afraid.
