### ISSUE TITLE
Slurp functionality

### ISSUE THREAD

**Issue by librarianmage** [mwilliamson/jq.py#17]
In [the jq manual](https://stedolan.github.io/jq/manual/), it describes a way to run the filter on the entire string at once instead each JSON object. Is this functionality present in this?

**Comment by mwilliamson** [comment]
No, there's no support for slurp. Mind if I ask what your use case is?

**Comment by MathWhiz** [comment]
I am trying to combine multiple JSON arrays (in strings) into one, and
while reading on the jq documentation, which I am already using for its
more common uses, I noticed the "slurp" option.

**Comment by MathWhiz** [comment]
By looking further into the manual, I found that `.[0] + .[1]` does exactly what I need.

**Comment by metashock** [comment]
Can this being re-opened? My use case is to replace Subprocess calls to `jq` by using this extension. This requires that the extension offer the same feature set as the command line binary. Just from a short look into the source code of `jq` it should being possible to use the slurp mode with the library.

**Comment by mwilliamson** [comment]
What's your use case? Just trying to understand why explicitly passing in an array wouldn't work.

**Comment by metashock** [comment]
Let's say you have this input:

    {"name":"Bob Dylan", "tags":"{Artist}{Singer}"}{"name": "Michael Jackson"}

Which is not valid json but a stream of valid json objects. The following `jq` command:

```sh
jq -s . input.txt
```

gives you a valid json array:

```json
[
  {
    "name": "Bob Dylan",
    "tags": "{Artist}{Singer}"
  },
  {
    "name": "Michael Jackson"
  }
]
```

**Comment by mwilliamson** [comment]
Ah, I see. Seems reasonable. I don't really have time to add new functionality, but feel free to make a pull request.

**Comment by metashock** [comment]
@mwilliamson Ok. Let me dig into it.. I'll give my best! :)

**Comment by peterthomassen** [comment]
This relates to `--slurpfile` which allows reading in and processing multiple files. The can be referred to using variables in the jq filter:
```
jq -n --slurpfile old $1 --slurpfile new $2 '{old: $old[0], new: $new[0]}'
```

If someone was working on slurp functionality, it may be worth considering this as well.

My use case is computing a JSON that represents something like the diff between old and new.

**Comment by henricook** [comment]
+1 - I was using this library through `urlwatch` and wanted to be able to slurp as I'm handling a list of objects (not wrapped in an array) from an HTTP endpoint

**Comment by mwilliamson** [comment]
I've added slurp functionality and released a prerelease version to PyPI. Feedback would be welcome!

**Comment by BYK** [comment]
@mwilliamson any plans on releasing the slurp-enabled version as a full release?

**Comment by BYK** [comment]
Well, don't know about the case above but it certainly works for me and works as expected 🙂

**Comment by mwilliamson** [comment]
This has now been released as part of 1.5.0.

**Comment by peterthomassen** [comment]
Thanks, @mwilliamson! :tada:

From the code, I gather that referring to different inputs using variables in the jq filter, like in `jq`, hasn't been implemented:

```sh
jq -n --slurpfile old $1 --slurpfile new $2 '{old: $old[0], new: $new[0]}'
```

Is that right? -- I can open a separate feature request issue for that, just would like to make sure.

(My use case is computing a JSON that represents [something like the diff between two inputs](https://github.com/desec-io/desec-tools/blob/main/rrsets_diff.sh#L54-L71), which currently requires invocation of `jq` as a separate process.)

**Comment by mwilliamson** [comment]
Correct, the change is only to add the `slurp` argument to `input_text()`.
