### ISSUE TITLE
jq install fails from pypi mirror without internet access

### ISSUE THREAD

**Issue by virtuald** [mwilliamson/jq.py#19]
Instead of downloading the jq tarball at install time, it seems like it would be better to download the jq tarball as part of setup only if the file doesn't exist, and include it as part of the uploaded tarball to pypi. This has the positive side effect of ensuring that issues such as #11 cannot happen in the future, regardless of what the jq project does with its source code.

For example, I do something similar in this project: https://github.com/robotpy/robotpy-wpilib/blob/master/hal-roborio/setup.py

**Comment by mwilliamson** [comment]
I've added support for wheels on Linux and Mac OS X in the latest version. Hopefully they work for you, but shout if not!
