### ISSUE TITLE
Installing jq onto  Windows

### ISSUE THREAD

**Issue by lbrader** [mwilliamson/jq.py#20]
The library looks great.  I'm doing development in Python on windows.  And not sure how to install this on Windows as a python library.   I took at the setting up on the Linux side.  And didn't figure out how to deploy this to Windows.  Any links to help? Thanks

**Comment by mwilliamson** [comment]
I'm afraid I don't have much experience with Python on Windows, and none with installing C extensions on Windows, so can't offer any useful advice.

**Comment by lbrader** [comment]
Thanks for fast turn around.   Let me ask around various folks.  If I get an answer I'll post it back here.

**Comment by mewalig** [comment]
someone's hiring to solve this: https://www.upwork.com/jobs/~0147f3bb893b8bb615

**Comment by BurnoHoffmann** [comment]
http://www.dowdandassociates.com/blog/content/howto-install-jq/
This url will help you.

**Comment by BurnoHoffmann** [comment]
I installed jq on windows using following method.
At first, I installed Chocolatey.
Using "choco install jq -version 1.5", I installed jq on windows.
Thanks,
Burno

**Comment by philpep** [comment]
Any news on this ? I tried to dig into this issue and it seems that oniguruma 6.8.2 can compile on windows (with make_win64.bat & visual cpp) but jq seems to compile only with mingw so I guess this will be an issue. Maybe compile all with mingw is the best choice here ?

**Comment by mrjcleaver** [comment]
A wheel for Windows would be wonderful. 

It's a bit warful to wequire  a workaround.

**Comment by Jiehong** [comment]
I've installed jq by downloading the jq binary from the jq website, and put it somewhere in the windows PATH.

This works, as I can use jq in any terminal now.

However, if I try to do `pip install jq`, it will still try to build a wheel for it (and fail in my case). Why would it need to build wheels if jq is already installed on the system?

**Comment by Avinash-Bhat** [comment]
@Jiehong jq.py needs to link to the underlying library of jq. A simple downloading and install doesn't do that.

PS: if you want to, you can just use `subprocess` to [invoke](https://gitlab.com/Avinash-Bhat/jqpy/-/blob/master/main.py#L25) the command from python. Not the cleanest way to do things, but will get things done on Windows

**Comment by iuyt9003** [comment]
How to install in windows when working with python, pip install jq is giving errors still couldn't solve it :(

**Comment by iuyt9003** [comment]
ERROR: Failed building wheel for jq                                                                                   
ERROR: Could not build wheels for jq, which is required to install pyproject.toml-based projects 
some magic that can solve this, that I am unaware of ?

**Comment by MatrixManAtYrService** [comment]
Ugh. I really don't want to remove jq as a dependency, it's really nice to use the same language for json manipulation as I do at the CLI, but I'm not about to go tell my new users that they have to use a different OS, nor do I want to add an external dependency and engage in `if windows:` nonsense.

**Comment by jknockel** [comment]
I have built some wheels using mingw/msys against both python 3.10 and 3.11 here:

https://www.cs.unm.edu/~jeffk/jq/

These have had very little testing, so please use at your own risk.

To get jq.py to build I had to apply a number of hacks against the jq and jq.py source code.  While I could probably go back and turn these into patches by guarding the changes with "if windows then XXX" sorts of conditions, perhaps more problematic was that in the process of building these I also came across a number of issues with python itself [1, 2], which ultimately led me to discover that mingw/msys is not supported by python [3].  While I was in turn able to work around these issues with additional hacks, the existence of these issues with python itself would seem to disfavor mingw/msys ever being an official build target of jq.py, although it clearly is not impossible to build jq.py using mingw/msys with enough effort.

[1] https://bugs.python.org/issue28267
[2] https://stackoverflow.com/a/57109148
[3] https://bugs.python.org/issue45538

**Comment by reivaxy** [comment]
> I have built some wheels using mingw/msys against both python 3.10 and 3.11 here:

Thank you so much for that, you rock (at my own risk is much better than not at all)

**Comment by baterflyrity** [comment]
@jknockel , can you please share building instructions for windows or maybe build jq for python 3.12?

**Comment by jknockel** [comment]
> @jknockel , can you please share building instructions for windows or maybe build jq for python 3.12?

Sure.  In fact, I don't know if it's due to changes in python 3.12 or due to improvements to mingw64, but the number of changes I had to make were much fewer this time:

https://github.com/jknockel/jq.py/tree/mingw-build

To build the wheel from an msys bash shell:

```
cython3 jq.pyx
python setup.py build --compiler=mingw32
python setup.py bdist_wheel
```

I've also uploaded the 3.12 wheel here:

https://www.cs.unm.edu/~jeffk/jq/

Again, this build has had very little testing, so please use at your own risk.

**Comment by baterflyrity** [comment]
@jknockel , thanks. You really helped me to solve it with 3.11 and 3.12.
Seems like I will some time rollout my own python binding that "just works".

**Comment by du33169** [comment]
@jknockel Sorry to bother after so long. 
Thanks to your instructions, I finally built a wheel under **MSYS2 UCRT64**. 
It worked well in the same MSYS2 environment and even passed all the tests after some adjustments. 
However, when I tried to `pip install` it to a native windows python environment, it reported:
```bash
ERROR: jq-1.7.0-cp311-cp311-mingw_x86_64_ucrt.whl is not a supported wheel on this platform.
```
I suppose renaming it is not a proper solution.
I've noticed that the wheel you provide on https://www.cs.unm.edu/~jeffk/jq/ has the correct platform identifier `win_amd64` and can be properly installed/imported, but you did mention that it was built under msys bash as well.

Please tell me if I've missed something, thanks!

**Comment by du33169** [comment]
> Looks like you may have already found a solution, but to clarify a few details that may be relevant, in my procedure I used the MSVCRT version of mingw not the UCRT version, and I used python as provided by the standard python installer on python.org, not an msys-packaged version of python.

Thanks! Actually I turned to standard python shortly after that as well. 
MSYS2 follows the convention of prefixing libraries with `lib`(see [msys2 wiki](https://www.msys2.org/wiki/Porting/#library-prefixes)). 
Consequently, any .pyd binary built under MSYS2 will link to `libpython3.xx.dll`, leading to `DLL load failed` when trying to install and import jq.py to a standard python environment, which provides `python3xx.dll`.
These two files are actually identical, and one can eliminate the error by manually editing the dll(pyd) dependency name using tools like [CEF Explorer](https://ntcore.com/explorer-suite/). This is some kind of "hacky" so these details are recorded just for future reference.

These days I'm trying to turn the whole process into github action flows, possibly opening a PR once everything's working fine.

**Comment by mwilliamson** [comment]
I've just published 1.8.0a2, which includes Windows wheels. Reports of success or failure using those wheels are gratefully received!

**Comment by dracozombie19** [comment]
I just installed on Windows 11 successfully.  I also ran a script with all of the asserts from the README and they all passed.

**Comment by mwilliamson** [comment]
> > I've just published 1.8.0a2, which includes Windows wheels. Reports of success or failure using those wheels are gratefully received!
> 
> Windows 10 x64 Python 3.12 - still installation error.

Just to check: you're trying to install the prerelease version? If so, could you post what the error you're getting?

**Comment by baterflyrity** [comment]
> > > I've just published 1.8.0a2, which includes Windows wheels. Reports of success or failure using those wheels are gratefully received!
> > 
> > 
> > Windows 10 x64 Python 3.12 - still installation error.
> 
> Just to check: you're trying to install the prerelease version? If so, could you post what the error you're getting?

sry, prerelease is installed successfully

**Comment by mwilliamson** [comment]
Thanks for the reports, 1.8.0 is now out with Windows wheels. Thanks again to all who helped put this together!

**Comment by mwilliamson** [comment]
It looks like using the latest setup-msys2 action version, and therefore later versions of msys2, causes linking failures. I've put some details in #132, but unfortunately don't really have the time to investigate much further, nor do I have a Windows machine to test on (and relying on GitHub Actions makes trying things out slow).

If anyone on this issue has any insight, it would be much appreciated! Otherwise, there's a risk that support for Windows wheels might have to be dropped eventually if, for whatever reason, using the pinned version of msys2 stops working.
