### ISSUE TITLE
Getting pretty-printed JSON out of jq

### ISSUE THREAD

**Issue by i-s-o-g-r-a-m** [mwilliamson/jq.py#21]
Hi,

I needed, in the context of a Python program, to canonicalize and pretty-print some JSON, and thought I would try using jq.py (since jq on its own supports these features, ie `jq -S "."`. I couldn't seem to make this happen with jq.py so ended up resorting to using `subprocess` to call `jq` directly. Did I miss something in the docs, or is my use case not supported?

Thanks!

**Comment by mwilliamson** [comment]
Nope, the Python bindings doesn't currently do pretty printing. Why not use the builtin `json` module in Python?

**Comment by i-s-o-g-r-a-m** [comment]
Ah, you mean like `json.dumps(some_json, indent=True, sort_keys=True)`? Man, I'm kicking myself now! Thanks for pointing that out! Good to know for the future! <sheepish grin>
