### ISSUE TITLE
setup.py compiler failure under ubuntu 16.10

### ISSUE THREAD

**Issue by headdab** [mwilliamson/jq.py#25]
A snippet of the error which likely shows enough information to determine why is included below:

creating build/lib.linux-x86_64-3.5
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro 
-Wl,-Bsymbolic-functions -Wl,-z,relro -g -fdebug-prefix-map=/build/python3.5-6tVwKN/python3.5-3.5.2=. -fstack
-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.
5/jq.o /home/estes/pkg/jq-0.1.6/jq-jq-1.5/.libs/libjq.a /home/estes/pkg/jq-0.1.6/onig-install-5.9.6/lib/libon
ig.a -o build/lib.linux-x86_64-3.5/jq.cpython-35m-x86_64-linux-gnu.so
/usr/bin/ld: i386 architecture of input file `/home/estes/pkg/jq-0.1.6/jq-jq-1.5/.libs/libjq.a(execute.o)' is
 incompatible with i386:x86-64 output
.... MANY MORE SIMILAR ERRORS

**Comment by headdab** [comment]
Likely a gcc v6 issue...

**Comment by mwilliamson** [comment]
It seems like you're building for a 64-bit build of Python, but jq has been built as a 32-bit library. I probably won't have time to take a proper look at this, but hopefully that gives somewhere to start investigating (assuming my interpretation is correct!)

**Comment by headdab** [comment]
That's my thoughts, and I recently upgraded to Ubuntu 16.10, so maybe it
has something to do with that.

**Comment by mwilliamson** [comment]
So it was working fine on previous versions of Ubuntu?

**Comment by headdab** [comment]
I've got a laptop that is an earlier version and will check that soon.

**Comment by mwilliamson** [comment]
I've added support for wheels on Linux and Mac OS X in the latest version. Hopefully they work for you, but shout if not!
