### ISSUE TITLE
accessing the jsonpath string from within the compiled jq object

### ISSUE THREAD

**Issue by algrebe** [mwilliamson/jq.py#26]
I was wondering if its possible to add a variable to access the jsonpath string.

The most common example I see is
```python
from jq import jq

jq(".").transform("42")
```

However, in some of my programs, I perform the transform operation many times. In that case, I usually do

```python
from jq import jq

j = jq(".")

j.transform("42")
j.transform("6")
```

The problem is, when something fails, I'd like to access the jsonpath string (in this case `"."`) and log it.

**Comment by mwilliamson** [comment]
Given that it's straightforward to retain the string within the calling code, I'm inclined to keep the library itself simple and let the caller keep the string if they need to. Is there a reason this wouldn't be practical for you?

**Comment by algrebe** [comment]
@mwilliamson thank you for the quick reply !

Not impractical but just an extra step.
I consider this compiled form similar to the regex compile version, where they have an [internal field called pattern](https://docs.python.org/2/library/re.html#re.RegexObject.pattern).

As the number of jq objects increase, I'll have to maintain a dictionary of object to original string.

I also feel that having the original string will make the `repr` of the object much more readable, which is useful when logging / raising exceptions.

**Comment by mwilliamson** [comment]
master now has the `program_string` attribute on programs.
