### ISSUE TITLE
Bug with map on array

### ISSUE THREAD

**Issue by adgaudio** [mwilliamson/jq.py#27]
Hello!

This is a great library.  Thank you for providing it!

I found the following inconsistency between jq on bash, and in this library:

bash
```
$ echo '[1,2,3,4]' | jq '.[]'
1
2
3
4

```

python
```
In [87]: z = [1,2,3,4]

In [88]: jq('.[]').transform(z)
Out[88]: 1
```

versions:
```
 $ pip freeze|grep jq
jq==0.1.6

$ jq --version
jq-1.5
```

In python, the return value should be an array.  Is there something I am doing incorrectly?  Is there a version mismatch?

**Comment by mwilliamson** [comment]
You probably need to set `multiple_output` to `True`. From the README:

> If `multiple_output` is `False` (the default), then the first output is used:
> 
> ```python
> jq(".[]+1").transform([1, 2, 3]) == 2
> ```
>
> If `multiple_output` is `True`, all output elements are returned in an array:
>
> ```python
> jq(".[]+1").transform([1, 2, 3], multiple_output=True) == [2, 3, 4]
> ```

**Comment by adgaudio** [comment]
Oh my I feel silly!  Sorry for wasting your time, and thank you for the explanation.

**Comment by z00m1n** [comment]
Shouldn't `multiple_output=True` be the default ? After all, that's how the command line `jq` behaves, so users (such as myself) would typically expect that, would't they ?
