### ISSUE TITLE
Question: possible to create non-programmatic transformations?

### ISSUE THREAD

**Issue by SandyWalsh** [mwilliamson/jq.py#3]
Great to see this binding. Thanks for making it!

I was wondering, how hard do you think it would be to define the transformation pipeline via a small grammar instead of programmatically?

For example, define the transformation in a json/yaml doc and have the pipeline created from that (vs. hand-crafted python code). 

I'd like to make our transformations data-driven.

**Comment by mwilliamson** [comment]
Closing since I don't think there's anything that needs to be done. Feel free to reopen if I'm mistaken!
