### ISSUE TITLE
Trouble installing through a proxy

### ISSUE THREAD

**Issue by mcandre** [mwilliamson/jq.py#30]
In setup.py, `urlretrieve()` does not appear to respect proxy environment variables, unlike `urlopen()`. This has the unfortunate consequence of making `pip install jq` fail in firewalled premises.

**Comment by shdobxr** [comment]
@mcandre what is the error that you are getting ?

**Comment by mwilliamson** [comment]
I've added support for wheels on Linux and Mac OS X in the latest version. Hopefully they work for you, but shout if not!

Also, `setup.py` now uses `requests` to fetch tarballs, which will hopefully work a little better.
