### ISSUE TITLE
create wheels?

### ISSUE THREAD

**Issue by AlJohri** [mwilliamson/jq.py#32]
@mwilliamson would it be possible to create wheels for the latest macos/python? this way we won't need to do `brew install autoconf automake libtool` to use the package

**Comment by AlJohri** [comment]
@mwilliamson just bumping this issue. I would be happy to help set it up if you're willing

**Comment by crashvb** [comment]
I too would find this useful.

**Comment by lukasheinrich** [comment]
I am also innterested in this and happy to help out

**Comment by mwilliamson** [comment]
I've added support for wheels on Linux and Mac OS X in the latest version. Hopefully they work for you, but shout if not!
