### ISSUE TITLE
pip install fails mac os mojave with SSL error

### ISSUE THREAD

**Issue by colhndchck** [mwilliamson/jq.py#34]
Hi,

Tried to installed jq via pip on Mac OS Majove (10.14.4) and I'm getting an SSL error.  Can we get a fix for this?  All of my autorconf and libtool libraries are up to date. Thanks.

error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)>

**Comment by RodneyMarable** [comment]
This certificate failure could prevent the jq Python bindings from being used in corporate environments, so it would be great if someone could take a look into fixing this.

**Comment by mwilliamson** [comment]
What URL is the command failing on? The only URLs referenced directly in `setup.py` are GitHub URLs, which I'd expect to have valid certificates.

Are you sure you have certificates installed correctly? The [release notes for Python 3.6](https://www.python.org/downloads/release/python-360/) mention:

> macOS users: If you are using the Python 3.6 from the python.org binary installer linked on this page, please carefully read the Important Information displayed during installation; this information is also available after installation by clicking on /Applications/Python 3.6/ReadMe.rtf. There is important information there about changes in the 3.6.0 installer-supplied Python, particularly with regard to SSL certificate validation.

If you haven't already, you might need to install the certificates e.g. for Python 3.6:

```
/Applications/Python\ 3.6/Install\ Certificates.command
```

If that doesn't work, I'm unlikely to have time to implement a fix in the bindings themselves in the near future.

**Comment by colhndchck** [comment]
We got around the SSL cert issue by downloading the files locally, but for some reason the setup.py is failing because it can't find jq.c.  See make command below.  Ran python setup.py install

Executing: make
/Library/Developer/CommandLineTools/usr/bin/make  all-am
  GEN      version.h
  CC       main.o
  CC       locfile.lo
  CC       bytecode.lo
  CC       compile.lo
  CC       execute.lo
  CC       builtin.lo
  CC       jv.lo
  CC       jv_parse.lo
  CC       jv_print.lo
  CC       jv_dtoa.lo
  CC       jv_unicode.lo
  CC       jv_aux.lo
  CC       jv_file.lo
  CC       jv_alloc.lo
  CC       jq_test.lo
  CC       util.lo
  CC       linker.lo
  CC       parser.lo
  CC       lexer.lo
  CCLD     libjq.la
  CCLD     jq
  GEN      jq.1
building 'jq' extension
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I./libressl-2.2.7/include -I./libressl-2.2.7/include -I/Users/bfeeser/sourcecode/jq.py/jq-jq-1.5 -I/Users/bfeeser/.pyenv/versions/3.6.7/include/python3.6m -c jq.c -o build/temp.macosx-10.14-x86_64-3.6/jq.o
clang: error: no such file or directory: 'jq.c'
clang: error: no input files
error: command 'clang' failed with exit status 1

**Comment by mwilliamson** [comment]
I've added support for wheels on Linux and Mac OS X in the latest version. Hopefully they work for you, but shout if not!
