### ISSUE TITLE
Bundled JQ 1.6 not manylinux compatible

### ISSUE THREAD

**Issue by henryiii** [mwilliamson/jq.py#43]
The following steps:

```bash
docker run --rm -it ubuntu:16.04
apt update && apt install python3 python3-pip
pip3 install jq
python3 -c "import jq"
```

produce this error:

```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /usr/local/lib/python3.5/dist-packages/jq.cpython-35m-x86_64-linux-gnu.so: symbol scalbln, version GLIBC_2.2.5 not defined in file libc.so.6 with link time reference
```

@lukasheinrich and @matthewfeickert noticed this trying to run on Travis. Note that on Travis JQ 1.5 is already available. When building the wheel, running repair_wheel on the JQ binary should have detected this issue.

FYI, this is the manylinux2010 wheel, but I assume both of them have this problem.

**Comment by lukasheinrich** [comment]
thanks @henryiii for this summary. would there be an easy  fix for this? (I'm a bit out of my depth here )

**Comment by henryiii** [comment]
I expect it's just an environment variable that needs to be set or something similar, and `cibuildwheel` should be outputting something from the internal repair_wheel step. I won't be able to help with it for a while, though, in the middle of a project with a deadline. :/.

**Comment by Cedric-M** [comment]
I confirm to have the exact same issue @henryiii faced

**Comment by mwilliamson** [comment]
I've just released 1.0.1a1, which uses `-lm` when building the extension in an attempt to fix the issue as suggested in https://github.com/joerick/cibuildwheel/issues/343. Could you give it a try and see if it works?

**Comment by lukasheinrich** [comment]
Thanks @mwilliamson! this weems to work using the recipe given by @henryiii

**Comment by mwilliamson** [comment]
Great, I'll make a 1.0.1 release. Thanks for taking a look.

**Comment by matthewfeickert** [comment]
> Great, I'll make a 1.0.1 release.

Things are working great now. Thank you for being super responsive, @mwilliamson!

**Comment by mwilliamson** [comment]
Great!
