### ISSUE TITLE
Recent performance changes

### ISSUE THREAD

**Issue by bmacphee** [mwilliamson/jq.py#44]
I have a use case that involves calling jq about a hundred times over.  Measuring versus 0.1.9a1 (the last version where I can verify performance is similar to previous versions), 1.0.0a4 added about an order of magnitude of time to my benchmark, and 1.0.0.a5 added another order of magnitude.

Does this have a workaround or something that should be changed on my side?  For now, I'll pin to 0.1.8 until I have time to investigate further.

**Comment by mwilliamson** [comment]
The only change between 1.0.0a4 and 1.0.0a5 that would affect performance is updating to jq 1.6. I'm not sure about the other performance issues. The API was rewritten, so there may be some unintended inefficiencies.

**Comment by mwilliamson** [comment]
Without any examples, it's a bit tricky to say!

**Comment by bmacphee** [comment]
Thanks for the speedy reply.  I will be happy to provide some more information soon, when I get some time to investigate.  I will also try to rule out the jq dependency itself.  I was not able to verify the earlier 1.0 versions due to an import error.  Presumably the module API changed slightly and was fixed in a4.

**Comment by bmacphee** [comment]
Just some preliminary testing I did so far:

1.0.1: new and old api work the same
```
python -m timeit -s 'import jq; p=jq.compile("[.[]+1]")' 'p.input([1, 2, 3]).first()'
10 loops, best of 3: 30.2 msec per loop
python -m timeit -s 'from jq import jq; p=jq("[.[]+1]")' 'p.transform([1, 2, 3])'
10 loops, best of 3: 30.9 msec per loop
```

1.0.0a4: most recent version that was in the ~1ms performance range
```
python -m timeit -s 'from jq import jq; p=jq("[.[]+1]")' 'p.transform([1, 2, 3])'
1000 loops, best of 3: 1.61 msec per loop
```

1.0.0a1: first change in performance
```
python -m timeit -s 'import jq; p=jq.compile("[.[]+1]")' 'p.input([1, 2, 3]).first()'
1000 loops, best of 3: 1.59 msec per loop
```

0.1.9a1: last version where I measured microsecond-level calls
```
python -m timeit -s 'from jq import jq; p=jq("[.[]+1]")' 'p.transform([1, 2, 3])'
100000 loops, best of 3: 10.1 usec per loop
```

this might be mostly due to changes from jq 1.5 to jq 1.6, but note the "compile" part is included in measurements here, whereas it is left out of the python benchmarks.
```
time echo "[1, 2, 3]" | ./jq16 "[.[]+1]"
[
  2,
  3,
  4
]
```
real	0m0.026s
user	0m0.026s
sys	0m0.000s
```
```
time echo "[1, 2, 3]" | jq "[.[]+1]"
[
  2,
  3,
  4
]

real	0m0.004s
user	0m0.004s
sys	0m0.000s
```

**Comment by bmacphee** [comment]
I know these are not especially precise measurements, but I can see that jq 1.6 has a higher startup cost... possibly the compile cost - but that was omitted from my measurements of the python wrapper.

The per-json entity processing time appears to be similar though.  (The delta between the two input files shown here).
Note the inputs were generated like this:
```
python3 -c 'print("\n".join([str([x, x+1, x+2]) for x in range(1000)]))' > input1000.json
```

```
time jq151 "[.[]+1]" input1.json 1>/dev/null

real	0m0.003s
user	0m0.003s
sys	0m0.000s
time jq151 "[.[]+1]" input1000.json 1>/dev/null

real	0m0.008s
user	0m0.008s
sys	0m0.000s
time ./jq16 "[.[]+1]" input1.json 1>/dev/null

real	0m0.028s
user	0m0.024s
sys	0m0.004s
time ./jq16 "[.[]+1]" input1000.json 1>/dev/null

real	0m0.031s
user	0m0.031s
sys	0m0.000s
```

**Comment by bmacphee** [comment]
Next I'll probably try to profile the wrapper code to see if I can pinpoint the thing responsible for the differences, but if this is not an intended use of the wrapper, don't keep this issue open just for my use case.  If it's python overhead I may be better off with a different wrapper, and if it's jq call overhead, I probably just have no choice but to stick with jq1.5 until I can pass multiple JSON objects in one call.

**Comment by mwilliamson** [comment]
It's likely because the program string gets recompiled on each call since, depending on how the program gets used, the result of compilation can't be shared between different calls. I've added in some pooling of programs which should help under some circumstances. If you'd like to test, I've uploaded 1.0.2a1 as a source distribution, and the wheels should hopefully finish building soon: https://travis-ci.org/github/mwilliamson/jq.py/builds/701048795

**Comment by bmacphee** [comment]
I wasn't going to get to this until tomorrow, but since you made the update, I gave it a try.  It looks like your recent change has a big impact and it's actually about 10% faster in the sample test case I was using versus the 0.1.x versions.
```
python -m timeit -s 'import jq; p=jq.compile("[.[]+1]")' 'p.input([1, 2, 3]).first()'
100000 loops, best of 3: 9.08 usec per loop
```

I will try with some bigger programs and inputs tomorrow, but I think this explains the behaviour I observed.

**Comment by bmacphee** [comment]
I've been able to confirm 1.0.2a1 holds up performance-wise to the 0.x versions using some of the larger jq inputs.  It seems like there's a slight call overhead reduction - not really 10%, but it looks like 10% on very small jq programs.

**Comment by mwilliamson** [comment]
1.0.2 has been released which should have improved performance.
