### ISSUE TITLE
Regex in compile doesn't escape "."

### ISSUE THREAD

**Issue by clowe-r7** [mwilliamson/jq.py#45]
I am trying to do a regex to search for ips and a ValueError/compile error is thrown when executing the below code:

`
import jq

re1 = '127\\\\.'

match = "127.0.0.1"

query = jq.compile(re1).input(match).all()

print(query)
`

Traceback
`Traceback (most recent call last):
  File "/Users/project/path/components/troubleshooting/test.py", line 7, in <module>
    query = jq.compile(re1).input(match).all()
  File "jq.pyx", line 56, in jq.compile
  File "jq.pyx", line 160, in jq._Program.__cinit__
  File "jq.pyx", line 131, in jq._JqStatePool.__cinit__
  File "jq.pyx", line 84, in jq._compile
  File "jq.pyx", line 72, in jq._compile
  File "jq.pyx", line 78, in jq._compile
ValueError: jq: error: syntax error, unexpected INVALID_CHARACTER, expecting $end (Unix shell quoting issues?) at <top-level>, line 1:
127\.   
jq: 1 compile error`

**Comment by mwilliamson** [comment]
Could you give an example of how you'd use jq (as in the command line tool) to do what you're looking for? It seems like the program you've written would just return the string `127\.` If you're trying to filter, I'd imagine you want to do something like:

```
jq.compile(r'select(test("127\\."))')
```

**Comment by clowe-r7** [comment]
So this would be the command line
`jq '.asset_names[] | test("127\\.|10\\.|172\\.1[6-9]\\.|172\\.2[0-9]\\.|172\\.3[0-1]\\.|192\\.168\\.")' test`

and test looks like this

{
  "asset_names": [
    "127.0.0.1",
    "127.0.0.1",
    "127.0.0.1",
    "127.0.0.1",
    "127.0.0.1"
  ]
}

**Comment by clowe-r7** [comment]
> Could you give an example of how you'd use jq (as in the command line tool) to do what you're looking for? It seems like the program you've written would just return the string `127\.` If you're trying to filter, I'd imagine you want to do something like:
> 
> ```
> jq.compile(r'select(test("127\\."))')
> ```

I think this is the fix. I'm testing it on a few more things now, but so far it's working

**Comment by clowe-r7** [comment]
That was it. Thank you!
