### ISSUE TITLE
How does this compare to pyjq - https://github.com/doloopwhile/pyjq ?

### ISSUE THREAD

**Issue by adrianog** [mwilliamson/jq.py#53]
Why one or the other? Both seem maintained.
Thanks

**Comment by mwilliamson** [comment]
I can't say I'm particularly familiar with pyjq. Other than a different API, the main difference I spotted was in the availability of wheels on PyPI.

**Comment by mwilliamson** [comment]
I'm closing this since I don't think there's anything else to address?
