### ISSUE TITLE
Unexpected behavior getting first item of empty array

### ISSUE THREAD

**Issue by jcoster** [mwilliamson/jq.py#54]
I would have expected the following to return `None`:

```python
jq.compile(".[]").input([]).first()
```

but it instead raises a `StopIteration` exception:

```
>>> import jq
>>> jq.compile(".[]").input([]).first()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "jq.pyx", line 278, in jq._ProgramWithInput.first
  File "jq.pyx", line 309, in jq._ResultIterator.__next__
  File "jq.pyx", line 337, in jq._ResultIterator._ready_next_input
StopIteration
```

Is this the correct behavior and I'm misunderstanding the situation? Thanks!

Note: workaround is to use `.[0]` instead (see below), which correctly returns `None`, but I'd like the flexibility to fetch all with `.[]` and then have the option to just fetch the first with `.first`.

```python
jq.compile(".[0]").input([]).first()
# returns None
```

**Comment by mwilliamson** [comment]
Yes, this is intended (although apparently poorly documented!) behaviour.

At the moment, the alternative would be something like (untested!):

```python
next(iter(jq.compile(".[]").input([])), None)
```

**Comment by jcoster** [comment]
Good to know, thanks! Closing this issue.
