### ISSUE TITLE
Select support

### ISSUE THREAD

**Issue by mslinn** [mwilliamson/jq.py#55]
The Bash version of `jq` has a `select` option, which is accessed via a pipe. Is there a way to do something similar with `jq.py`, for example:
```python
jq.compile(f'.[] | select({expression} == {value})').input(my_json_data).text()
```

**Comment by mwilliamson** [comment]
What happens when you trying doing so at the moment with jq.py?

**Comment by mslinn** [comment]
This did what I wanted it to:
```python
jq.compile(f'.[] | select({expression} == {value})').input(text=dumpdata).all()
```
Seems jq.py delegates a lot of behavior to the underlying jq executable. Is that documented?

**Comment by mwilliamson** [comment]
The top of the README says:

> This project contains Python bindings for jq.

which is intended to convey that these are bindings, rather than (for instance) a reimplementation/port.

**Comment by mslinn** [comment]
Might want to call that out more explicitly, and point to the jq docs.
