### ISSUE TITLE
>32 bit numbers come across as floats.

### ISSUE THREAD

**Issue by scottyob** [mwilliamson/jq.py#56]
>>> import jq
>>> jq.compile(".").input({"foo": 2147483647}).first()
{'foo': 2147483647}
>>> jq.compile(".").input({"foo": 2147483648}).first()
{'foo': 2147483648.0}

**Comment by scottyob** [comment]
#57 should resolve this.

**Comment by chetanmelkani** [comment]
@mwilliamson Can this please be merged? I am unable to use the library without this change. Let me know if I can be of any help.

**Comment by scottyob** [comment]
@chetanmelkani I've created a fork @ https://github.com/scottyob/jq.py with a patch to start using jq master (not release 1.6) and with a slightly different patch.  Seems this project is fairly abandoned, and the jq C library itself hasn't had a release in ages.  In master, they've added support for decNumbers and keeping original numbers as a char*, so if you can pull down my link there instead that would be a much more preferred way of doing it.

**Comment by mwilliamson** [comment]
Thanks for the report, this should be addressed in master now.
