### ISSUE TITLE
Unicode content is being broken

### ISSUE THREAD

**Issue by mborsetti** [mwilliamson/jq.py#59]
As you can see from the following code (Python 3.8.6), jq breaks Unicode:

```
>>> import jq
>>> import json
>>> jsondata = json.loads('[{"title": "TPS™ Analyst", "company": "Any"}]')
>>> jqdata = jq.text('.[].title', jsondata)
>>> jqdata == jsondata[0]['title']
False
```

Indeed:
```
>>> print(jsondata[0]['title'], ',', jqdata)
TPS™ Analyst , "TPS\u2122 Analyst"
```

jq turned `™` into the string `\u2122`!

Nothing in the docs about this.

**Comment by mwilliamson** [comment]
By calling `.text()`, you're getting the resulting JSON back as JSON text, so `jqdata` contains the title as an encoded string. If you want to get JSON values, use `.first()` e.g.

```
>>> import jq
>>> import json
>>> jsondata = json.loads('[{"title": "TPS™ Analyst", "company": "Any"}]')
>>> jqdata = jq.first('.[].title', jsondata)
>>> jqdata == jsondata[0]['title']
True
```

**Comment by mborsetti** [comment]
@mwilliamson Thanks for the reply! Sorry for the lack of familiarity with `jq`, but am trying to fix a PR at https://github.com/thp/urlwatch/pull/626 such that it doesn't wreck Unicode.   

Based on your suggestion, do you see any problems with replacing the code

`return jq.text(subfilter['query'], json.loads(data))`

with

`return str(jq.first(subfilter['query'], json.loads(data))`?

I.e. are they equivalent in functionality, other than the first one breaking Unicode?

Thanks in advance!

**Comment by mwilliamson** [comment]
It depends on what output you want. If you want the output as JSON text, that is, you want the JSON encoded as a string, then you'll want to use `.text()`. If instead you want the JSON values, you'll want to use `.first()`.

To put it another way, `.text()` is roughly equivalent to using `.first()` followed by `json.dumps()`. `.first()` is roughly equivalent to using `.text()` followed by `json.loads()`.

**Comment by mborsetti** [comment]
Ah! Thanks.

I think this is the "roughly equivalent" Unicode-friendly code:

```
jq_first = jq.first(subfilter['query'], json.loads(data))
return json.dumps(jq_first, ensure_ascii=False)
```

Appreciated _very_ much.

**Comment by mborsetti** [comment]
Ah! Thanks.  Appreciated _very_ much.

However, it ended up not working, so I deep-dived into the code, and found the issue in line 272 (function `text` of class `_ProgramWithInput`). Instead of:
```
return "\n".join(json.dumps(v) for v in self)
```
it should be :
```
return "\n".join(json.dumps(v, ensure_ascii=False) for v in self)
```

In my case the workaround is to replace:
```
return jq.text(subfilter['query'], json.loads(data))
```
with:
```
return '\n'.join(json.dumps(v, ensure_ascii=False) for v in (jq.compile(subfilter['query'], json.loads(data)))
```
and magically Unicode is no longer broken (note the addition of `ensure_ascii=False`).

Here's an example:

this works:
```
>>> import jq
>>> import json
>>> data = '[{"title": "TPS™", "company": "Any"},{"title": "Two", "company": "Another"}]'
>>> jsondata = json.loads(data)
>>> '\n'.join(json.dumps(v, ensure_ascii=False) for v in (jq.compile('.[].title').input(jsondata)))
'"TPS™"\n"Two"'
```
and this doesn't:
```
>>> jq.text('.[].title', jsondata)
'"TPS\\u2122"\n"Two"'
```

May I suggest a fix so future users don't have to struggle with this?

Thanks!

**Comment by mwilliamson** [comment]
I'm afraid I don't see what the issue is. Both `"TPS™"` and `"TPS\u2122"` are valid JSON encodings of the same value:

```
json.loads(r'"TPS™"') == json.loads(r'"TPS\u2122"')
```

jq.py doesn't provide any particular guarantee about how those characters are encoded when producing text output, except that it will be valid JSON text. So far as I can tell, the output you've provided is valid rather than being broken Unicode.

If you care about exactly how those characters are encoded, you can use `json.dumps` with `ensure_ascii=False`.

**Comment by mborsetti** [comment]
You're missing an extra `\`:  `jq.text` returns `"TPS\\u2122"`, not `"TPS\u2122"`!

If you run the above code, you can see it by running
```
>>> print(jq.text('.[].title', jsondata))
"TPS\u2122"
"Two"
```
That doesn't work with humans.

The below instead works (with humans):
```
>>> print('\n'.join(json.dumps(v, ensure_ascii=False) for v in (jq.compile('.[].title').input(jsonda
ta))))
"TPS™"
"Two"
```

**Comment by mwilliamson** [comment]
> You're missing an extra `\`: `jq.text` returns `"TPS\\u2122"`, not `"TPS\u2122"`!

The JSON text is `"TPS\u2122"`, which can be represented in Python as `'"TPS\\u2122"'`, which is what gets printed out on the REPL. It's the same Python string i.e. 

```
>>> '"TPS\\u2122"' == r'"TPS\u2122"'
True
```

> That doesn't work with humans.
>
> The below instead works (with humans):

I'm not sure I see the issue with using `json.dumps()`? It seems like you've got working code.

**Comment by mborsetti** [comment]
> I'm not sure I see the issue with using `json.dumps()`? It seems like you've got working code.

No issue. I am just sharing the solution for others to use should the main code not be updated to support Unicode JSON natively.
