### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [mwilliamson/jq.py#61]
Problem
---------
On aarch64, ‘pip install jq’ builds the wheels from source code and then installs it. It requires the user to have a development environment installed on his system. Also, it takes some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, ‘pip install jq’ should download the wheels from pypi

@mwilliamson Please let me know your interest in releasing aarch64 wheels. I can help with this.

**Comment by mwilliamson** [comment]
This should be covered by the latest release.
