### ISSUE TITLE
Unexpected list of lists returned for 'keys'

### ISSUE THREAD

**Issue by butsuri43** [mwilliamson/jq.py#67]
Hi there,

I stumped across a bit unexpected behavior when trying to get keys of a dictionary:
```
In [2]: jq.all("keys",{"test1":"1234","test2":2345})
Out[2]: [['test1', 'test2']]
```
while 'jq' on bash gives just the list of keys:
```
$ echo '{"test1":"1234","test2":2345}' | jq 'keys'
[
  "test1",
  "test2"
]
```
The same discrepancy is present also for `keys_unsorted`.
Seen for (jq==1.1.2).

**Comment by mwilliamson** [comment]
jq can output multiple JSON values, for instance:

```
$ echo '[1, 2, 3]' | jq '.[]'
1
2
3
```

In the Python bindings, `.all()` returns all of those output values as a list:

```
>>> import jq
>>> jq.all(".[]", [1, 2, 3])
[1, 2, 3]
```

Since your program only produces one output value, then the output of `.all()` will be a singleton list. If you only want the first value, you can use `.first()`:

```
>>> jq.first("keys",{"test1":"1234","test2":2345})
['test1', 'test2']
```

**Comment by butsuri43** [comment]
Thanks for clarification. Indeed I would naively expect `keys` to be realized as `keys | .[]` but I see now how this would in fact be wrong.

All the best and thanks for the great package!
