### ISSUE TITLE
jq does not properly install its peer dependencies (and relies on a third-party library in setup.py)

### ISSUE THREAD

**Issue by tisto** [mwilliamson/jq.py#68]
# Steps to reproduce

## Create a virtual env and install jq:

````
python3 -m venv .
bin/pip install jq
````

## Try to import the requests library:

````
bin/python
Python 3.8.10 (default, May  4 2021, 03:06:52)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'requests'
````

This is causing problems when we are trying to use jq as a peer dependency in our OS project (plone.org) and when we build Docker containers.

I think it is generally not recommended to use a third-party library in setup.py if I am not mistaken. Since this can cause all kinds of problems because you never know how people might install your package and which versions they might use.

Thanks for sharing the library with the OS world! We would love to continue to use jq in our OS project. Though, it would be really important to fix this IMHO (not only for us but for everyone who uses the library).

**Comment by mwilliamson** [comment]
Could you post the output when you attempt to install the library?

**Comment by tisto** [comment]
@mwilliamson sure:

````
 bin/pip install jq
Collecting jq
  Using cached jq-1.2.1-cp38-cp38-macosx_10_9_x86_64.whl (368 kB)
Installing collected packages: jq
Successfully installed jq-1.2.1
WARNING: You are using pip version 21.1.1; however, version 21.3 is available.
You should consider upgrading via the '/Users/timo/workspace/wtf/bin/python3 -m pip install --upgrade pip' command.
````

**Comment by tisto** [comment]
Just a follow up. I upgraded my pip version to a version that supports pyproject.toml:

https://pip.pypa.io/en/stable/news/#v21-2

The problem still persists though.

Maybe packages that rely on pyproject.toml should declare this in their setup.py and fail hard on old pip versions. Something like this line could help:

https://github.com/plone/plone.restapi/blob/master/setup.py#L6

**Comment by mauritsvanrees** [comment]
To reproduce the problem though:

```
$ python3.9 -mvenv .
$ bin/pip install pip<20
$ bin/pip install --no-binary :all: jq
```

Wow, this even fails for me because `setuptools` cannot be found. :-)
This works:

```
$ bin/pip install --no-binary jq,requests jq
```

I guess on some platforms this could fail when `requests` itself cannot be installed for whatever reason via source, and there is no wheel available on PyPI.

**Comment by mwilliamson** [comment]
The dependencies are part of the sdist now, so this shouldn't be an issue any more.
