### ISSUE TITLE
[feature request]: args on input rather than compile?

### ISSUE THREAD

**Issue by itcarroll** [mwilliamson/jq.py#69]
To run one jq program having a `$` variable with many values, I currently do:

```
[jq.compile('.id = $x', args={'x': x}).input({'id': None}).first() for x in range(10)]
```

Could it be faster if your API allowed the args parameter on `input`? As in:
```
program = jq.compile('.id = $x')
[program.input({'id': None}, args={'x': x}).first() for x in range(10)]
```

**Comment by mwilliamson** [comment]
As I recall, the args are passed during compilation in jq proper, so the Python bindings just inherit that behaviour.

**Comment by itcarroll** [comment]
Ah, I see. Thanks for reviewing.
