### ISSUE TITLE
Specifying options like in CLI? Alternative workarounds?

### ISSUE THREAD

**Issue by DEV-ONI** [mwilliamson/jq.py#71]
Thanks for making this project!
I'm currently using this module on a webserver, and was wondering if there was a way to specify directories such as in the CLI:

`-Ldirectory / -L directory:
Prepend directory to the search list for modules. If this option is used then no builtin search list is used. See the section on modules below`

Im unsure if there's a way to do that through this module, but was wondering if there were any alternatives. I was hoping to specify my functions in a `.jq` module in my project's directory. How do you normally handle custom functions in your projects?

**Comment by mwilliamson** [comment]
No, there's currently no way to do so.

> How do you normally handle custom functions in your projects?

Somewhat unhelpfully, I don't actually use jq in any projects at the moment.

**Comment by DEV-ONI** [comment]
Thanks for the answer!
