### ISSUE TITLE
Installation fails for python3.11 due to old cython dependency

### ISSUE THREAD

**Issue by veruu** [mwilliamson/jq.py#75]
Steps to reproduce:

- grab any environment with python3.11, e.g. a Fedora rawhide container
- run `pip install jq`

Full output: https://gitlab.com/-/snippets/2401208/raw/main/snippetfile1.txt

Relevant part is at the end of the output:

```
      jq.c:198:12: fatal error: longintrepr.h: No such file or directory
        198 |   #include "longintrepr.h"
            |            ^~~~~~~~~~~~~~~
      compilation terminated.
```

This issue was reported for cython: https://github.com/cython/cython/issues/4461 and was fixed with cython 0.29.25

The cython dependency is currently hardcoded to 0.29.24: https://github.com/mwilliamson/jq.py/search?q=cython
Updating it to 0.29.25 or above should fix the problem.

**Comment by mwilliamson** [comment]
Thanks for the report, this should be addressed in the latest version.
