### ISSUE TITLE
Preserve decimal precision

### ISSUE THREAD

**Issue by tom-wegener** [mwilliamson/jq.py#80]
Hey, thank you for the library.

At the moment the official jq preserves decimal precision like this:
```bash
> echo '{"tmp": 1.00 }' | jq .tmp
1.00
```

while this library does not preserve the decimal precision:
```python
>>>jq.first('.tmp', {"tmp": 1.00})
1
```

I think this is at least undocumented behaviour and should be mentioned or fixed.

I believe this happens because of the conversion in line 87 of jq.pyx.
I would argue that the decision if a value should be int or not (and most other type-conversions) should happen on the user-site.

**Comment by mwilliamson** [comment]
That doesn't seem to be the behaviour I see on jq 1.6:

```
$ echo '{"tmp": 1.00 }' | jq .tmp
1
```

**Comment by tom-wegener** [comment]
Yeah, the problem is that there was no release of jq for some time, so every rather new version is 1.6 with more or less patches.

The version of, for example, Fedora is a bit more true to the master-branch because it has more recent patches.

On 6. Jan 2023, at 22:23, Michael Williamson ***@***.***> wrote:

﻿

That doesn't seem to be the behaviour I see on jq 1.6:

$ echo '{"tmp": 1.00 }' | jq .tmp
1

**Comment by mwilliamson** [comment]
The intent is to match jq 1.6 behaviour, so I think this is working as intended.
