### ISSUE TITLE
poetry2nix derivation fails when building jq

### ISSUE THREAD

**Issue by MatrixManAtYrService** [mwilliamson/jq.py#81]
Hi.  Thanks for maintaining this project, I really like it.

This may fall under the "not my problem" category.  I'll totally understand if you want to just close it outright.  But I was hoping you might be able to shed some light on the issue which will let me figure out how to move forward.  

The gist is: there's something odd about the build for jq.py and it's causing problems with [poetry2nix](https://github.com/nix-community/poetry2nix).

I'm using nix to manage non-python dependencies of an application which depends on jq.  I've simplified the issue to just three files:

```python3
# src/jqdepender/hello.py
import jq
print("hello world")
```

```toml
# pyproject.toml
[tool.poetry]
name = "jqdepender"
description = "says hello world, but imports jq first"
version = "0.1.0"
authors = ["some guy"]
packages = [{include = "jqdepender", from = "src"}]


[tool.poetry.dependencies]
python = "^3.11"
jq = "^1.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

```nix
# flake.nix
{
  description = "a dummy package which depends on jq";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs?rev=b68bd2ee52051aaf983a268494cb4fc6c485b646";
  };

  outputs = { self, nixpkgs, flake-utils }: (flake-utils.lib.eachSystem [ "x86_64-linux" "x86_64-darwin"] (system:
    let
      pkgs = nixpkgs.legacyPackages.${system};
    in
    rec {
      packages.jqdepender = pkgs.poetry2nix.mkPoetryApplication {
        projectDir = ./.;
      };

      # 'nix build' fails currently due to a jq-related error
      # instead run
      # % nix develop
      # # poetry build
      defaultPackage= packages.jqdepender;

      devShell = pkgs.mkShell {
        buildInputs = [
          pkgs.python311
          pkgs.poetry
        ];
      };
    }));
}
```

I can build my "application" like so:
```
% nix develop  # makes python and poetry available
$ poetry build  # uses poetry to build the app
```

I'd like to be able to build it like so:
```
% nix build
```

But instead I get this output:
```
error: builder for '/nix/store/sqbih2pq27xmymmi93i3cwdznyiims9c-python3.10-jq-1.3.0.drv' failed with exit code 1;
       last 10 log lines:
       > unpacking source archive /nix/store/q8w1gp24aj6yxvxpxw9js4401lwhxjwf-jq-1.3.0.tar.gz
       > source root is jq-1.3.0
       > setting SOURCE_DATE_EPOCH to timestamp 1663602695 of file jq-1.3.0/setup.cfg
       > patching sources
       > applying patch /nix/store/bl2zkysigpqv59h1cvw20wcx2p7vhyjy-jq-py-setup.patch
       > patching file setup.py
       > Hunk #1 FAILED at 1.
       > Hunk #2 succeeded at 104 with fuzz 1 (offset -16 lines).
       > Hunk #3 succeeded at 119 with fuzz 1 (offset -17 lines).
       > 1 out of 3 hunks FAILED -- saving rejects to file setup.py.rej
       For full logs, run 'nix log /nix/store/sqbih2pq27xmymmi93i3cwdznyiims9c-python3.10-jq-1.3.0.drv'.
error: 1 dependencies of derivation '/nix/store/jqfm3ir1q6lvgzzkc2blk02z7amwhlid-python3.10-jqdepender-0.1.0.drv' failed to build
```

The referenced logs look like this:
```
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing pip-build-hook
Using pipBuildPhase
Using pipShellHook
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/q8w1gp24aj6yxvxpxw9js4401lwhxjwf-jq-1.3.0.tar.gz
source root is jq-1.3.0
setting SOURCE_DATE_EPOCH to timestamp 1663602695 of file jq-1.3.0/setup.cfg
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
applying patch /nix/store/bl2zkysigpqv59h1cvw20wcx2p7vhyjy-jq-py-setup.patch
patching file setup.py
Hunk #1 FAILED at 1.
Hunk #2 succeeded at 104 with fuzz 1 (offset -16 lines).
Hunk #3 succeeded at 119 with fuzz 1 (offset -17 lines).
1 out of 3 hunks FAILED -- saving rejects to file setup.py.rej
```

I thought about filing an issue at [poetry2nix](https://github.com/nix-community/poetry2nix) but they have a message up that redirects me to [this](https://github.com/nix-community/poetry2nix/blob/master/docs/edgecases.md) page.

Do you have any idea what might cause this and if anything can be done to fix it?

**Comment by MatrixManAtYrService** [comment]
I've had a chat with the poetry2nix guys in their matrix channel.  They pointed me to this code:

https://github.com/nix-community/poetry2nix/blob/6cf6701a4844041528bba6973b801bda753d5b43/overrides/default.nix#L888-L896

And proposed this workaround:
> You can reapply the patch (^) manually on the [jq.py](http://jq.py/) version that you are using, and add it to poetry2nix with a version gate. But it will likely break again in the future.

And this more permanent solution:
>  Z: A better way is to submit a PR upstream that allows disabling the online fetching in [setup.py](http://setup.py/) with an environment variable (or some kind of option). Then our override can just be setting this environment, plus adding the required dependencies with Nix.
>
> Me: So this would be a PR againset poetry2nix which changes the derivation that you linked to above such that it provides the needed dependencies more explicitly?
>
> Z: It will be a PR against [jq.py](http://jq.py/) itself so we can cleanly disable the online fetching without resorting to patching.

**Comment by mwilliamson** [comment]
jq 1.3.0 doesn't download any files in `setup.py` -- the dependencies are now included in the source distribution.

**Comment by MatrixManAtYrService** [comment]
Oh that's good to know.  It explains why I couldn't figure out how to add the option to removes it.

Perhaps I just need to remove the now-unnecessary code on the other side.

**Comment by mwilliamson** [comment]
I haven't looked at the patch that's being applied -- it's possible that it patches out the use of the local instance of jq entirely, in which case it's still probably needed (with adjustments).

**Comment by MatrixManAtYrService** [comment]
A comment from that chat:

> However, it would be nice if upstream supported a way to directly use the system libjq, instead of building its own.

and another:

> wait what... There is anoyhter pyjq that does the same thing! https://github.com/doloopwhile/pyjq/tree/master/dependencies


If this bugs me again in the future I might revisit it and attempt to update that patch, but it's a bit over my head at the moment so I don't think I'll be fixing it this week or even this month.  What that means about the status of this issue, I leave up to @mwilliamson

**Comment by mwilliamson** [comment]
I've just pushed an update to master that should address this. Specifically, you should now be able to set the environment variable `JQPY_USE_SYSTEM_LIBS` to `1` to use the system libs rather than building and using the bundled libs.

**Comment by mwilliamson** [comment]
I'm closing this since `JQPY_USE_SYSTEM_LIBS` should hopefully address this issue, feel free to say if that's not the case and I can reopen.
