### ISSUE TITLE
how can I package this so that it can be reused as Lambda Layer in AWS?

### ISSUE THREAD

**Issue by pohti** [mwilliamson/jq.py#83]
As usual way of creating custom Layers in AWS Lambda,
I have uploaded the zipped up `jq.cpython-310-x86_64-linux-gnu.so`.
But I am still not able to ```import jq``` in my Lambda code.

What am I doing wrong?

**Comment by mwilliamson** [comment]
I don't use AWS Lambda, so I'm afraid I have no particular advice to give. If you have more details of exactly what you've tried, or what results you're seeing, then I might be able to help, but as is I don't think there's any help I can provide.
