### ISSUE TITLE
'OverflowError: cannot convert float infinity to integer' when handling big numbers

### ISSUE THREAD

**Issue by itokarev70** [mwilliamson/jq.py#84]
Greetings,

I have some code that relies on the specific way _jq_ is handling big numbers.
For example, if an operation result exceeds `max double`, _jq_ will still return a `max double`:

_jq 1.6:_ 
```
jq '{"result": (.input * 2)}'
{"input": 1.7976931348623157e+308}
{
  "result": 1.7976931348623157e+308
}
```

However, it looks like this behavior changed in _jq.py_ v1.1.0, and is now different from _jq_ 1.6.

_jq.py 1.3.0:_
```
python -c "import jq; print(jq.compile('{\"result\": (.input * 2)}').input({\"input\": 1.7976931348623157e+308}).first())"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "jq.pyx", line 288, in jq._ProgramWithInput.first
  File "jq.pyx", line 324, in jq._ResultIterator.__next__
  File "jq.pyx", line 87, in jq._jv_to_python
OverflowError: cannot convert float infinity to integer
```

Older versions of jq.py (v1.0.2) behave similarly to _jq_:

_jq.py 1.0.2:_
```
python -c "import jq; print(jq.compile('{\"result\": (.input * 2)}').input({\"input\": 1.7976931348623157e+308}).first())"
{'result': 1.7976931348623157e+308}
```

What could be some of the ways to have the pre-1.1.0 behavior - other than pinning v1.0.2? 
Is this something that could be supported (again) in some future versions?
Thank you!

**Comment by mwilliamson** [comment]
Thanks for pointing this out, the NaN, Inf and -Inf should be outputted as None, DBL_MAX and -DBL_MAX respectively now (matching the behaviour of jq 1.6).

**Comment by itokarev70** [comment]
Awesome, 1.4.0 works as expected. Really appreciate the quick resolution.
Thank you!

**Comment by mwilliamson** [comment]
No worries, I'm glad it works!
