### ISSUE TITLE
walk built-in function does not work

### ISSUE THREAD

**Issue by cogitaria-admin** [mwilliamson/jq.py#86]
The built-in walk function has does not work.  The filter compiles but has zero impact. 

```
json = '{ "foo": 1, "bar": { "x": 42 }, "baz": 8 }'
filter = jq.compile('walk(if type == "object" and has("x") then "success" else . end)')
print(filter.input(json).first())
```
The result shows no changes occurred:

`{ "foo": 1, "bar": { "x": 42 }, "baz": 8 }`

If you run the same filter with the same input using jq on command line you get the expected result:

`{ "foo": 1, "bar": "success", "baz": 8 }`

**Comment by mwilliamson** [comment]
You're passing in a JSON string as input, so the walk has no effect since the singular input value doesn't match `type == "object"`. You can either parse the input before calling `.input()`, or pass the string as JSON text:

```
json = '{ "foo": 1, "bar": { "x": 42 }, "baz": 8 }'
filter = jq.compile('walk(if type == "object" and has("x") then "success" else . end)')
print(filter.input(text=json).first())
```
