### ISSUE TITLE
Is there a way to output query result without quotes (i.e. "jq -r ")

### ISSUE THREAD

**Issue by zhuangxy** [mwilliamson/jq.py#88]
Hi, 
Is there a way to output query result without quotes (i.e. "jq -r ")

**Comment by mwilliamson** [comment]
Does getting the value back as a JSON value (rather than JSON text) do what you want? For instance:

```
jq.compile(".").input("hello").first()
```

will give the string `"hello"` i.e. a string that doesn't contain any quotes.
