### ISSUE TITLE
Tests failing with jq-1.7

### ISSUE THREAD

**Issue by miallo** [mwilliamson/jq.py#93]
Hello!
With jq-1.7 there are some changes breaking the current tests:
https://github.com/mwilliamson/jq.py/blob/53b4c25087aa1b62f1bf3c5feace21c28f529418/tests/jq_tests.py#L26
will fail with an error now
```sh
> echo 0 | jq "0/0"
jq: error (at <stdin>:1): number (0) and number (0) cannot be divided because the divisor is zero
```
instead 
```sh
> echo 0 | jq "nan"
null
```
works (and is backwards compatible to at least 1.6)

Also the error of "expecting $end" was changed to "expecting end of file", so both of the following test cases are failing:
https://github.com/mwilliamson/jq.py/blob/53b4c25087aa1b62f1bf3c5feace21c28f529418/tests/jq_tests.py#L197
https://github.com/mwilliamson/jq.py/blob/53b4c25087aa1b62f1bf3c5feace21c28f529418/tests/jq_old_tests.py#L77

Change made in jq in the commit https://github.com/jqlang/jq/commit/6d694a4a581a2d3a6014711c691a23b6dce9badc in the file [parser.c](https://github.com/jqlang/jq/blob/7a72f58d2e92254652162ec7ca1b3074e3a22c35/src/parser.c#L975). So far the test cases do not seem to be jq-version specific, so I am not exactly sure how to deal with this.

**Comment by mwilliamson** [comment]
Thanks for the report, I've just pushed some changes to master that should add support jq 1.7.
