### ISSUE TITLE
Behaviour of Out Method first() on JSON Array Output 

### ISSUE THREAD

**Issue by tobiasschweizer** [mwilliamson/jq.py#95]
Hi there,

First of all: jq.py seems to be the missing part I have been looking for so I can get of my mess of bash jq constructs and Python scripts interfacing via files ...

I have a question related to the output method `first`: 
`assert jq.compile("[.[]+1]").input_value([1, 2, 3]).first() == [2, 3, 4]`

https://github.com/mwilliamson/jq.py#output-methods

Here, the `jq` expression is wrapped by square brackets and thus returns an array. So the whole array is treated as one element and returned as a whole. I found this counterintuitive since I would have expected 2. 

However, written like this `jq.compile(".[]+1").input_value([1, 2, 3]).first()` it would return 2. `jq.compile(".[]+1").input_value([1, 2, 3]).all()` would then again be the same as  `jq.compile("[.[]+1]").input_value([1, 2, 3]).first() == [2, 3, 4]`.

Does this behaviour stem from the fact that `jq` may return valid JSON but also just text, depending on the expression being used? 

Thanks for your feedback.

**Comment by mwilliamson** [comment]
At a high level, jq accepts some number of JSON values, and outputs some number of JSON values. For instance, here's bash accepting and outputting three JSON values (specifically, 1, 2 and 3):

```
$ echo -e '1\n2\n3\n' | jq
1
2
3
```

These Python bindings reflect that behaviour. If you call `.first()`, you get the first JSON value, if you call `.all()`, you get all of the JSON values.
