### ISSUE TITLE
tox.ini missing in sdist - please add

### ISSUE THREAD

**Issue by mandree** [mwilliamson/jq.py#96]
Greetings, I am packaging jq 1.6.0 from the download tarball for FreeBSD.
I figured that I need to download and use tox.ini separately when I want to run self-tests "as I always did" in prior releases (where I downloaded jq 1.2.1's tests).

Please consider also adding tox.ini to the source tarballs for future releases, as a follow-up to https://github.com/mwilliamson/jq.py/commit/bb95e4133cd3cf470358cd29c95e246f6f5c9262

Thank you.

**Comment by mwilliamson** [comment]
`tox.ini` is now included in the sdist, which should hopefully resolve this issue.
